apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: role-binding
  namespace: user0
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: full-access-user0
subjects:
- kind: ServiceAccount
  name: sa-user0
  namespace: user0
