apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: node-access
  namespace: user0
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: node-access
subjects:
- kind: ServiceAccount
  name: sa-user0
  namespace: user0
