apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: role-binding
  namespace: user1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: full-access-user1
subjects:
- kind: ServiceAccount
  name: sa-user1
  namespace: user1
